/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  martinasalis
 * Created: 14-lug-2017
 */

--DB: ammdb ; user: martinasalis ; pass: martinasalis;


CREATE TABLE postType (
    posttype_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    posttype_name VARCHAR(32)
);

CREATE TABLE users (
    user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256) UNIQUE,
    surname VARCHAR(256) UNIQUE,
    birthday DATE,
    presentation VARCHAR(1024),
    urlFotoProfilo VARCHAR(256),
    password VARCHAR(256) NOT NULL
);

CREATE TABLE groups (
    group_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256)
);

CREATE TABLE users_groups (
    user_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    group_id INTEGER,
    FOREIGN KEY (group_id) REFERENCES groups(group_id),
    PRIMARY KEY (user_id, group_id)
);

CREATE TABLE post (
    post_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(1024),
    type INTEGER,
    FOREIGN KEY (type) REFERENCES postType(postType_id),
    urlPost VARCHAR(256),
    user_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    group_id INTEGER,
    FOREIGN KEY (group_id) REFERENCES groups(group_id)
);


INSERT INTO posttype (posttype_id, posttype_name)
VALUES (default, 'IMAGE');

INSERT INTO posttype (posttype_id, posttype_name)
VALUES (default, 'LINK');

INSERT INTO users(user_id, name, surname, birthday, presentation, urlFotoProfilo, password)
VALUES(
    default,
    'Gino',
    'Marras',
    '1965-03-13',
    'ciao',
    'img/gino.jpg',
    '123'
);

INSERT INTO users(user_id, name, surname, birthday, presentation, urlFotoProfilo, password)
VALUES(
    default,
    'Lucilla',
    'Martis',
    '1999-11-09',
    'ciao',
    'img/lucilla.jpg',
    '123'
);

INSERT INTO users(user_id, name, surname, birthday, presentation, urlFotoProfilo, password)
VALUES(
    default,
    'Lollo',
    'Canu',
    '1990-01-25',
    'ciao',
    'img/lollo.jpg',
    '123'
);

INSERT INTO post (post_id, content, type, urlPost, user_id, group_id)
VALUES (
    default, 
    '“La vita deve essere vissuta, non controllata;
     e l’umanità è vinta se continua a giocare di fronte ad una sconfitta certa”',
     null,
     '',
     1,
     null
);

INSERT INTO post (post_id, content, type, urlPost, user_id, group_id)
VALUES (
    default, 
    'Jiggaly...puff...jiggaly...puff!
     Jiggaly...puff...jiggaly...',
     1,
     'img/jigglypuff.jpg',
     2,
     null
);

INSERT INTO post (post_id, content, type, urlPost, user_id, group_id)
VALUES (
    default, 
    '“Because maybe, you''re gonna be the one that saves me 
     And after all, you''re my wonderwall”',
     2,
     'https://www.youtube.com/watch?v=bx1Bh8ZvH84',
     3,
     null
);


INSERT INTO groups (group_id, name)
VALUES (
    default, 
    'Amici degli animali'
);

INSERT INTO groups (group_id, name)
VALUES (
    default, 
    'Giramondo'
);

INSERT INTO users_groups (user_id, group_id)
VALUES (
    2, 
    1
);

INSERT INTO users_groups (user_id, group_id)
VALUES (
    3, 
    2
);